Added unit-of-work
project-origin/wallet pull request #15
Opened 2023-05-10 13:53 UTC by MartinSchmidt

2023-05-12 11:05 UTC, duizer requested changes
The github workflow does not finish within 2hours.

2023-05-12 11:05 UTC, duizer requested changes
The github workflow does not finish within 2hours.

2023-05-22 07:22 UTC, tnickelsen approved these changes

2023-05-22 07:56 UTC, duizer commented on src/ProjectOrigin.Wallet.IntegrationTests/TestClassFixtures/PostgresDatabaseFixture.cs
> +    public virtual Task InitializeAsync()
Why is this marked as virtual?

2023-05-22 07:58 UTC, duizer commented on src/ProjectOrigin.Wallet.Server/Program.cs
>  app.MapGet("/", () => "Communication with gRPC endpoints must be made through a gRPC client. To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909");
This line is also defined in Startup

2023-05-22 07:59 UTC, duizer commented on src/ProjectOrigin.Wallet.Server/Program.cs
> +app.MapGrpcService<WalletService>();
Should this be in Startup?

2023-05-22 08:03 UTC, MartinSchmidt commented on src/ProjectOrigin.Wallet.IntegrationTests/TestClassFixtures/GrpcHelpers/ForwardLoggingProvider.cs
> +    internal class ForwardingLoggerProvider : ILoggerProvider
It ensures that logs from the running service can be forwarded to the log output when running the tests.

2023-05-22 09:09 UTC, duizer commented on src/ProjectOrigin.Wallet.IntegrationTests/TestClassFixtures/GrpcTestFixture.cs
> +        }
Is the GrpcTestContext needed? This method is never called and it is the only place where the GrpcTestContext is constructed.

2023-05-22 11:25 UTC, duizer approved these changes

2023-05-22 11:25 UTC, merged